export const T = Object.freeze({
  IDENT:'IDENT', STR:'STR', NUM:'NUM',
  EQ:'EQ', LT:'LT', GT:'GT',
  '<>':'<>', '<=':'<=', '>=':'>=', '!=':'!=',
  PLUS:'PLUS', MINUS:'MINUS', STAR:'STAR', SLASH:'SLASH',
  LPAREN:'LPAREN', RPAREN:'RPAREN', COMMA:'COMMA', SEMI:'SEMI', DOT:'DOT',
  AND:'AND', OR:'OR', NOT:'NOT',
  SELECT:'SELECT', FROM:'FROM', WHERE:'WHERE', JOIN:'JOIN',
  LEFT:'LEFT', RIGHT:'RIGHT', INNER:'INNER', OUTER:'OUTER', CROSS:'CROSS',
  ON:'ON', GROUP:'GROUP', BY:'BY', HAVING:'HAVING',
  ORDER:'ORDER', ASC:'ASC', DESC:'DESC', LIMIT:'LIMIT', OFFSET:'OFFSET',
  AS:'AS', DISTINCT:'DISTINCT', IN:'IN', BETWEEN:'BETWEEN',
  IS:'IS', NULL:'NULL', LIKE:'LIKE',
  COUNT:'COUNT', SUM:'SUM', AVG:'AVG', MIN:'MIN', MAX:'MAX',
  EOF:'EOF',
});

export const SQL_KEYWORDS = new Set(Object.keys(T));